(require 'dirvish)
(add-to-list 'load-path (expand-file-name "site-lisp/dirvish/extensions" user-emacs-directory))

(require 'dirvish-collapse)
(require 'dirvish-emerge)
(require 'dirvish-history)
(require 'dirvish-icons)
(require 'dirvish-ls)
(require 'dirvish-narrow)
(require 'dirvish-peek)
(require 'dirvish-quick-access)
(require 'dirvish-rsync)
(require 'dirvish-side)
(require 'dirvish-subtree)
(require 'dirvish-vc)
(require 'dirvish-yank)

(dirvish-override-dired-mode)
(setq dirvish-attributes '(file-size-human-readable))
